# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2346717a087093e17bd2246294f629bb"
name = "youtube-proxy"
handle = "youtube-proxy"
application_url = "https://lang-notebook-actually-accounts.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ohsolutions.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://lang-notebook-actually-accounts.trycloudflare.com/auth/callback",
  "https://lang-notebook-actually-accounts.trycloudflare.com/auth/shopify/callback",
  "https://lang-notebook-actually-accounts.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
